package com.buffalo.Buffalo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/buffalo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
    private BuffaloRepository buffaloRepository;

    //@PostMapping(path="/add") // Map ONLY POST Requests
    //public @ResponseBody String addNewStarwars (@RequestParam String name
    //    , @RequestParam boolean sith, @RequestParam boolean hasForce) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

      //Starwars n = new Starwars();
      //n.setName(name);
      //n.setSith(sith);
      //n.sethasForce(hasForce);
      //starwarsRepository.save(n);
      //return "Saved";
    //}

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Buffalo> getAllBuffalo() {
    // This returns a JSON or XML with the users
      return buffaloRepository.findAll();
    }
  }

